/* The playlist, hand-cleaned.
 *
 * Scraped from the YouTube playlist, then titles and artists were tidied by
 * hand — YouTube's own metadata is full of "(Official Video)", "- Topic"
 * channel names and inconsistent casing, none of which belong on screen.
 *
 * `id` is the YouTube video id. It is the only field the player needs; the
 * rest is for the UI. Cover art comes from i.ytimg.com/vi/<id>/… at runtime,
 * so adding a track means adding one line here and nothing else.
 */
window.TRACKS = [
  { id: 'u-YGV5xt-jk', title: 'Closer', artist: 'The Chainsmokers ft. Halsey' },
  { id: '0mjiJ4JlW1g', title: 'Lean On', artist: 'Major Lazer & DJ Snake ft. MØ' },
  { id: 'v16qZcBllUU', title: 'Sorry', artist: 'Justin Bieber' },
  { id: 'Z5uR4frdqd8', title: 'Love Yourself', artist: 'Justin Bieber' },
  { id: 'fdz_cabS9BU', title: 'Thinking Out Loud', artist: 'Ed Sheeran' },
  { id: 'DvjAyJ8Ztc4', title: "Don't Let Me Down", artist: 'The Chainsmokers ft. Daya' },
  { id: 'ah4jxqEUekI', title: 'Shape of You', artist: 'Ed Sheeran' },
  { id: 'BSBhT7YijUc', title: 'What Do You Mean?', artist: 'Justin Bieber' },
  { id: '1w8gDiJbRGw', title: 'Cheerleader (Felix Jaehn Remix)', artist: 'OMI' },
  { id: 'vXvVZt8MqaI', title: 'Let Me Love You', artist: 'DJ Snake ft. Justin Bieber' },
  { id: 'JPVAYKNB7zs', title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars' },
  { id: '3_g2un5M350', title: 'Starboy', artist: 'The Weeknd ft. Daft Punk' },
  { id: 'KEI4qSrkPAs', title: "Can't Feel My Face", artist: 'The Weeknd' },
  { id: 'YQHsXMglC9A', title: 'Hello', artist: 'Adele' },
  { id: 'K1FlAphL2p8', title: 'Stressed Out', artist: 'twenty one pilots' },
  { id: 'DqO1lLavWGo', title: 'Stitches', artist: 'Shawn Mendes' },
  { id: 'inCm3ByI17o', title: 'This Is What You Came For', artist: 'Calvin Harris ft. Rihanna' },
  { id: 'OUzOtZ7NPEo', title: 'Work', artist: 'Rihanna ft. Drake' },
  { id: 'cJtN1j2I8Zw', title: 'Work from Home', artist: 'Fifth Harmony ft. Ty Dolla $ign' },
  { id: 'd0eUMnJ5kTA', title: 'Faded', artist: 'Alan Walker' },
  { id: 'SlbfAYvA_gI', title: 'Photograph', artist: 'Ed Sheeran' },
  { id: 'vkX6yFVFRYY', title: 'Where Are Ü Now', artist: 'Skrillex & Diplo ft. Justin Bieber' },
  { id: 'uxpDa-c-4Mc', title: 'Hotline Bling', artist: 'Drake' },
  { id: '7hkL4zDCKhs', title: 'Stay With Me', artist: 'Sam Smith' },
  { id: '6p3E7OMw52g', title: "Can't Stop the Feeling!", artist: 'Justin Timberlake' },
  { id: '2vjPBrBU-TM', title: 'Chandelier', artist: 'Sia' },
  { id: '6wCe1Iv-a5E', title: 'Me, Myself & I', artist: 'G-Eazy x Bebe Rexha' },
  { id: 'xBrzatJ6QD4', title: 'The Hills', artist: 'The Weeknd' },
  { id: 'qSay_8xzijg', title: 'Treat You Better', artist: 'Shawn Mendes' },
  { id: 'oLeROuCMwj8', title: 'Heathens', artist: 'twenty one pilots' },
  { id: 'guHlCF3Ghi8', title: 'Love Me Like You Do', artist: 'Ellie Goulding' },
  { id: 'RG-D4bcg54s', title: 'Lush Life', artist: 'Zara Larsson' },
  { id: 'hSHIwmAnwGk', title: 'All of Me', artist: 'John Legend' },
  { id: 'R_BO8C05XLA', title: 'Radioactive', artist: 'Imagine Dragons' },
  { id: 'M4T_k33CI1M', title: 'Cake by the Ocean', artist: 'DNCE' },
  { id: 'ku16PsxpZGU', title: 'Rather Be', artist: 'Clean Bandit ft. Jess Glynne' },
  { id: '_GWKkqNoyEA', title: 'Counting Stars', artist: 'OneRepublic' },
  { id: 'TfdFUMxRzqU', title: 'Roses', artist: 'The Chainsmokers ft. ROZES' },
  { id: 'rkE_oBe8ABw', title: 'Fast Car', artist: 'Jonas Blue ft. Dakota' },
  { id: 'w1Smzzw_w7Q', title: 'Ride', artist: 'twenty one pilots' },
  { id: 'jGHnuvdp0Vc', title: 'Sugar', artist: 'Robin Schulz ft. Francesco Yates' },
  { id: 'fSKtPBRV1gE', title: 'Pillowtalk', artist: 'ZAYN' },
  { id: 'vWtERdMudzE', title: 'i hate u, i love u', artist: "gnash ft. olivia o'brien" },
  { id: 'Vik1dtQ0eHc', title: "Can't Hold Us", artist: 'Macklemore & Ryan Lewis ft. Ray Dalton' },
  { id: 'K9fISloOznc', title: 'Wake Me Up', artist: 'Avicii' },
  { id: '4u4d4GWdpo8', title: 'In the Name of Love', artist: 'Martin Garrix & Bebe Rexha' },
  { id: 'aDPkAK5s30I', title: 'Firestone', artist: 'Kygo ft. Conrad Sewell' },
  { id: '_Cx531UoYZU', title: 'Happy', artist: 'Pharrell Williams' },
  { id: 'ffqliB42Nh4', title: "We Don't Talk Anymore", artist: 'Charlie Puth ft. Selena Gomez' },
  { id: '0yW7w8F2TVA', title: "Say You Won't Let Go", artist: 'James Arthur' },
  { id: 'y4FiCl-tUJc', title: 'Demons', artist: 'Imagine Dragons' },
  { id: 'mOKqNxN4jWM', title: 'Middle', artist: 'DJ Snake ft. Bipolar Sunshine' },
  { id: 'JP7T67IyNsU', title: 'Stole the Show', artist: 'Kygo ft. Parson James' },
  { id: 'CtyytBCHA9U', title: 'Earned It', artist: 'The Weeknd' },
  { id: 'DWkN4eNUlJo', title: 'Needed Me', artist: 'Rihanna' },
  { id: 'SXiSVQZLje8', title: 'Side to Side', artist: 'Ariana Grande ft. Nicki Minaj' },
  { id: 'b0U-NcIWz1M', title: 'Bang Bang', artist: 'Jessie J, Ariana Grande & Nicki Minaj' },
  { id: 'mVw5KiGwqaQ', title: 'Rockabye', artist: 'Clean Bandit ft. Sean Paul & Anne-Marie' },
  { id: 'k3HJFFFJid0', title: 'Summer', artist: 'Calvin Harris' },
  { id: 'F7VBnbt0_-w', title: 'Dark Horse', artist: 'Katy Perry ft. Juicy J' },
  { id: 'GTyN-DB_v5M', title: 'Never Forget You', artist: 'Zara Larsson & MNEK' },
  { id: '9Gb0a8Ie2hM', title: 'Pompeii', artist: 'Bastille' },
  { id: 'tUUoS_j3wWw', title: 'Starving', artist: 'Hailee Steinfeld & Grey ft. Zedd' },
  { id: '2DC6xArPthg', title: 'Rude', artist: 'MAGIC!' },
  { id: 'dNzE0iy2mt8', title: 'Shut Up and Dance', artist: 'WALK THE MOON' },
  { id: 'z9boCCK7M8c', title: 'My House', artist: 'Flo Rida' },
  { id: 'aeb11lwQ9bo', title: 'No Money', artist: 'Galantis' },
  { id: '3uGha0RTWws', title: 'Blame', artist: 'Calvin Harris ft. John Newman' },
  { id: '7Gv3ABudl7A', title: 'A Sky Full of Stars', artist: 'Coldplay' },
  { id: 'WaFD7Gs75hQ', title: "Don't Wanna Know", artist: 'Maroon 5 ft. Kendrick Lamar' },
  { id: '67ibXO8viXE', title: "I'm Not the Only One", artist: 'Sam Smith' },
  { id: 'a16S-Ve8Teo', title: 'Am I Wrong', artist: 'Nico & Vinz' },
  { id: 'Lq-33dD1b4Q', title: 'GDFR', artist: 'Flo Rida ft. Sage the Gemini & Lookas' },
  { id: '6b0Y4AvS4Sg', title: 'Perfect Strangers', artist: 'Jonas Blue ft. JP Cooper' },
  { id: 'OFiBWFtbH-w', title: 'The Ocean', artist: 'Mike Perry ft. Shy Martin' },
  { id: 'ULIwsV3s9qc', title: 'This Girl', artist: "Kungs vs Cookin' on 3 Burners" },
  { id: '1ekZEVeXwek', title: 'Into You', artist: 'Ariana Grande' },
  { id: 'DCFEn10LWQo', title: 'All About That Bass', artist: 'Meghan Trainor' },
];

/* The line under the wordmark. Rotates on click — pure nostalgia bait, no
 * lyrics, just the texture of being alive in 2016. */
window.BUMPERS = [
  'when the aux was a responsibility',
  'phone on 4% and nobody owned a power bank',
  '3 a.m., streaks unbroken, this exact song',
  'the group chat was still one group chat',
  'everybody had the same three songs downloaded',
  'played it off a cracked screen in the back seat',
  'you knew every word and none of the meaning',
  'one earphone each, the good one to them',
  'the year the drop mattered more than the lyrics',
  'saved to a playlist you never renamed',
  'bluetooth cut out, so we went back to the cable',
  'summer holidays with nowhere to actually be',
];
